server:
  port: 5000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: post-service
          uri: http://post-service:4000
          predicates:
            - Path=/api/posts/**
        - id: comment-service
          uri: http://comment-service:4001
          predicates:
            - Path=/api/comments/**
        - id: even-bus
          uri: http://even-bus:4002
          predicates:
            - Path=/api/events/**
        - id: query-service
          uri: http://query-service:4003
          predicates:
            - Path=/api/query/**
