server:
  port: 4003

spring:
  application:
    name: QUERY-SERVICE
  zipkin:
    base-url: http://zipkin:9411/
  datasource:
    url: 'jdbc:h2:mem:query'
  jpa:
    defer-datasource-initialization: 'true'
    show-sql: 'true'
  h2:
    console:
      enabled: 'true'
  rabbitmq:
    host: rabbitmq

